{{- if eq .Values.global.registryLocation "on-cluster" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: drycc-registry-proxy
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  {{- if ge .Capabilities.KubeVersion.Minor "6" }}
  updateStrategy:
    type: RollingUpdate
  {{- end }}
  selector:
    matchLabels:
      app: drycc-registry-proxy
      heritage: drycc
  template:
    metadata:
      name: drycc-registry-proxy
      labels:
        heritage: drycc
        app: drycc-registry-proxy
    spec:
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
      containers:
      - name: drycc-registry-proxy
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/registry-proxy:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        {{- if or (.Values.limitsCpu) (.Values.limitsMemory)}}
        resources:
          limits:
            {{- if (.Values.limitsCpu) }}
            cpu: {{.Values.limitsCpu}}
            {{- end}}
            {{- if (.Values.limitsMemory) }}
            memory: {{.Values.limitsMemory}}
            {{- end}}
        {{- end}}
        env:
        - name: "DRYCC_REGISTRY_HOST"
          valueFrom:
            secretKeyRef:
              name: registry-secret
              key: host
        - name: "DRYCC_REGISTRY_USERNAME"
          valueFrom:
            secretKeyRef:
              name: registry-secret
              key: username
        - name: "DRYCC_REGISTRY_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: registry-secret
              key: password
        ports:
        - containerPort: 8080
          hostPort: {{.Values.global.registryProxyPort}}
{{- end }}
