{{- if eq .Values.global.registry_location "on-cluster" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: drycc-registry-proxy
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.image_tag }}
spec:
  {{- if ge .Capabilities.KubeVersion.Minor "6" }}
  updateStrategy:
    type: RollingUpdate
  {{- end }}
  selector:
    matchLabels:
      app: drycc-registry-proxy
      heritage: drycc
  template:
    metadata:
      name: drycc-registry-proxy
      labels:
        heritage: drycc
        app: drycc-registry-proxy
    spec:
{{- if (.Values.global.use_cni) }}
      hostNetwork: true
{{- end}}
      containers:
      - name: drycc-registry-proxy
        image: {{.Values.image_registry}}{{.Values.org}}/registry-proxy:{{.Values.image_tag}}
        imagePullPolicy: {{.Values.image_pull_policy}}
{{- if or (.Values.limits_cpu) (.Values.limits_memory)}}
        resources:
          limits:
{{- if (.Values.limits_cpu) }}
            cpu: {{.Values.limits_cpu}}
{{- end}}
{{- if (.Values.limits_memory) }}
            memory: {{.Values.limits_memory}}
{{- end}}
{{- end}}
        env:
        - name: REGISTRY_HOST
          value: $(DRYCC_REGISTRY_SERVICE_HOST)
        - name: REGISTRY_PORT
          value: $(DRYCC_REGISTRY_SERVICE_PORT)
        - name: BIND_ADDR
{{- if (.Values.global.use_cni) }}
          value: {{ default "127.0.0.1:5555" .Values.global.registry_proxy_bind_addr | quote }}
{{- else }}
          value: {{ default "80" .Values.global.registry_proxy_bind_addr | quote }}
{{- end }}
{{- if not (.Values.global.use_cni) }}
        ports:
        - containerPort: 80
          hostPort: {{.Values.global.registry_proxy_port}}
{{- end }}
{{- end }}
