{{- if eq .Values.global.registryLocation "on-cluster" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: drycc-registry-proxy
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  {{- if ge .Capabilities.KubeVersion.Minor "6" }}
  updateStrategy:
    type: RollingUpdate
  {{- end }}
  selector:
    matchLabels:
      app: drycc-registry-proxy
      heritage: drycc
  template:
    metadata:
      name: drycc-registry-proxy
      labels:
        heritage: drycc
        app: drycc-registry-proxy
    spec:
      containers:
      - name: drycc-registry-proxy
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/registry-proxy:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
{{- if or (.Values.limitsCpu) (.Values.limitsMemory)}}
        resources:
          limits:
{{- if (.Values.limitsCpu) }}
            cpu: {{.Values.limitsCpu}}
{{- end}}
{{- if (.Values.limitsMemory) }}
            memory: {{.Values.limitsMemory}}
{{- end}}
{{- end}}
        env:
        - name: REGISTRY_HOST
          value: $(DRYCC_REGISTRY_SERVICE_HOST)
        - name: REGISTRY_PORT
          value: $(DRYCC_REGISTRY_SERVICE_PORT)
        - name: BIND_ADDR
          value: {{ default "80" .Values.global.registry_proxy_bind_addr | quote }}
        ports:
        - containerPort: 80
          hostPort: {{.Values.global.registryProxyPort}}
{{- end }}
