{{- if eq .Values.global.registryLocation "on-cluster" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: drycc-registry-proxy
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: drycc-registry-proxy
      heritage: drycc
  template:
    metadata:
      name: drycc-registry-proxy
      labels:
        heritage: drycc
        app: drycc-registry-proxy
    spec:
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
      initContainers:
      - name: drycc-registry-init
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/python-dev:latest
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
        - netcat
        - -v
        - -a
        - $(DRYCC_REGISTRY_HOST)
        env:
        - name: "DRYCC_REGISTRY_HOST"
          valueFrom:
            secretKeyRef:
              name: registry-secret
              key: host
      containers:
      - name: drycc-registry-proxy
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/registry-proxy:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        {{- if .Values.diagnosticMode.enabled }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 10 }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 10 }}
        {{- end }}
        {{- if or (.Values.limitsCpu) (.Values.limitsMemory)}}
        resources:
          limits:
            {{- if (.Values.limitsCpu) }}
            cpu: {{.Values.limitsCpu}}
            {{- end}}
            {{- if (.Values.limitsMemory) }}
            memory: {{.Values.limitsMemory}}
            {{- end}}
        {{- end}}
        {{- if not .Values.diagnosticMode.enabled }}
        startupProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        {{- end }}
        env:
        - name: "DRYCC_REGISTRY_HOST"
          valueFrom:
            secretKeyRef:
              name: registry-secret
              key: host
        - name: "DRYCC_REGISTRY_USERNAME"
          valueFrom:
            secretKeyRef:
              name: registry-secret
              key: username
        - name: "DRYCC_REGISTRY_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: registry-secret
              key: password
        ports:
        - containerPort: 8080
          hostPort: {{.Values.global.registryProxyPort}}
{{- end }}
