imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "docker.io"
limitsCpu: "100m"
limitsMemory: "50Mi"

global:
  # Set the location of Workflow's Registry
  #
  # Valid values are:
  # - on-cluster: Run registry within the Kubernetes cluster
  # - off-cluster: Use registry outside the Kubernetes cluster (example: dockerhub,self-hosted)
  # - ecr: Use Amazon's ECR
  # - gcr: Use Google's GCR
  registryLocation: "on-cluster"
  # The host port to which registry proxy binds to
  registryProxyPort: 5555
  # Set the `listen` variable for registry-proxy's NGINX
  #
  # Valid values are:
  # - 80: If you're on flannel or kubenet
  # - 127.0.0.1:5555: If you're with CNI
  #
  # In case of CNI you can not use `hostPort` notation due to https://github.com/kubernetes/kubernetes/issues/23920
  # registry_proxy_bind_addr: "80"
  # If the Kubernetes cluster uses CNI
  # use_cni: true
